### ISSUE TITLE
Separate web app from library

### ISSUE THREAD

**Issue by haggen** [eshiota/retro-audio-js#3]
I would like to suggest to separate the library that parses the sheet music encoded in JSON from the application.

**Comment by eshiota** [comment]
@haggen When you say "application", you mean the page with the controls and the application instantiation? If so, I guess Github Pages is a good candidate to do that, what do you think (there's [an issue open](https://github.com/eshiota/retro-audio-js/issues/2) for that)?

**Comment by haggen** [comment]
Yeah, that's what I mean, so I could, for instance, use in my own web app. And sure, I think GH Pages is great. :)

BTW, I'm only talking in english because all the other issues were in english but I speak portuguese. :P

**Comment by eshiota** [comment]
Sure thing. =)

I'll close this issue, and it'll will be solved on #2.
