### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by jaydson** [eshiota/retro-audio-js#8]
While issue #2 is not done, update the [website experiment](http://eshiota.com/experiments/retrojs/) with the code that works on Firefox.

**Comment by eshiota** [comment]
From now on, the latest version will always be available here: http://eshiota.github.io/retro-audio-js/

**Comment by jaydson** [comment]
![](http://media.giphy.com/media/pNpONEEg3pLIQ/giphy.gif)
